### ISSUE TITLE
Throws an error on load-sample-documents

### ISSUE THREAD

**Issue by shark8me** [marcliberatore/mallet-lda#2]
I tried to run lda on the sample documents with the code example given in the README:

``` clojure
(ns mallet-topic-model.core
   (:require [marcliberatore.mallet-lda :refer [make-instance-list lda]]
            [marcliberatore.mallet-lda.misc :refer [load-sample-documents]]))

(lda (make-instance-list (load-sample-documents)))

```

I got the following error:

> Failed trying to require mallet-topic-model.core with: java.lang.NullPointerException: null
>                 misc.clj:29 marcliberatore.mallet-lda.misc/make-documents
>                 misc.clj:34 marcliberatore.mallet-lda.misc/load-sample-documents
>                 core.clj:13 mallet-topic-model.core/eval6264
> ..stacktrace elided.

and in the console:

> Perhaps the 'resources' directories weren't copied into the 'class' directory.
>  Continuing.

Perhaps the sample documents in the resources folder of this project isn't available when we just include this jar in our project.clj?

**Comment by marcliberatore** [comment]
Yes, that's the case. I'll update the documentation to reflect this fact.
